
CREATE TABLE CLIENTEPRODUTOPRECO (
    CLIEA13ID  CHAR(13) NOT NULL,
    PRODICOD   INTEGER NOT NULL,
    PRECO      NUMERIC(15,3) NOT NULL,
    REGISTRO   DATE
);

ALTER TABLE CLIENTEPRODUTOPRECO ADD CONSTRAINT PK_CLIENTEPRODUTOPRECO PRIMARY KEY (CLIEA13ID, PRODICOD);