ALTER TABLE NOTACOMPRAITEM ADD PERC_FCP_ST DOUBLE PRECISION;
ALTER TABLE NOTACOMPRAITEM ADD VALOR_FCP_ST DOUBLE PRECISION;
ALTER TABLE NOTACOMPRAITEM ADD PERC_FCP DOUBLE PRECISION;
ALTER TABLE NOTACOMPRAITEM ADD VALOR_FCP DOUBLE PRECISION;
ALTER TABLE NCM ADD PERC_FCP DOUBLE PRECISION;